version: "3.9"
services:
  myapp:
    build:
      context: .
    command: ["gunicorn", "__init__:app"]
    image: myapp
    healthcheck:
      test: ["CMD-SHELL", "curl -f --user-agent myapp-container-health-checker http://myapp:8000/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 2
      start_period: 5s
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./__init__.py
        target: /app/__init__.py
      - type: bind
        source: ./gunicorn.conf.py
        target: /app/gunicorn.conf.py
