version: "3.9"
services:
  myapp:
    build:
      context: .
    image: myapp
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./myapp.py
        target: /app/myapp.py
      - type: bind
        source: ./gunicorn_conf.py
        target: /app/gunicorn_conf.py
