version: "3.9"
services:
  myapp:
    build:
      context: .
    command: ["gunicorn", "__init__:app"]
    image: myapp
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./__init__.py
        target: /app/__init__.py
      - type: bind
        source: ./gunicorn.conf.py
        target: /app/gunicorn.conf.py
