version: "3.9"
services:
  myapp:
    build:
      context: .
    command: ["gunicorn", "__init__:app"]
    image: myapp
    healthcheck:
      test: ["CMD-SHELL", "curl -f --user-agent myapp-health-checker http://myapp:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 2
      start_period: 5s
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./__init__.py
        target: /app/__init__.py
      - type: bind
        source: ./gunicorn.conf.py
        target: /app/gunicorn.conf.py
  mock-elb:
    image: nginx:1.23
    healthcheck:
      test: ["CMD-SHELL", "curl -f --user-agent mock-elb-health-checker http://mock-elb/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 2
      start_period: 5s
    depends_on:
      myapp:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: default.conf
        target: /etc/nginx/conf.d/default.conf
