version: "3.9"
services:
  statsd-exporter:
    image: prom/statsd-exporter:v0.22.4
    ports:
      - "9125:9125"
      - "9102:9102"
    volumes:
      - type: bind
        source: ./configs/statsd/statsd.conf
        target: /statsd/statsd.conf
    command:
      - --statsd.mapping-config=/statsd/statsd.conf
  myapp:
    build:
      context: ./web/myapp
    command: ["gunicorn", "myapp:app"]
    image: myapp
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f --user-agent myapp-health-checker http://myapp:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 2
      start_period: 5s
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./web/myapp/project/__init__.py
        target: /app/project/__init__.py
      - type: bind
        source: ./web/myapp/myapp.py
        target: /app/myapp.py
      - type: bind
        source: ./web/myapp/gunicorn.conf.py
        target: /app/gunicorn.conf.py
  mock-elb:
    image: nginx:1.23
    healthcheck:
      test: ["CMD-SHELL", "curl -f --user-agent mock-elb-health-checker http://mock-elb/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 2
      start_period: 5s
    depends_on:
      myapp:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./configs/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./configs/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=lol
      - MYSQL_PASSWORD=lol
      - MYSQL_ROOT_PASSWORD=lol
      - MYSQL_USER=lol
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-plol", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 3s
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql

volumes:
  dbdata:
